// Copyright 2026 Zero Day AI, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"path/filepath"
	"runtime"
	"testing"

	astchecks "github.com/zero-day-ai/ast-checks"
)

// TestNoOsExitInHandler asserts that os.Exit() is never called outside of
// the CLI entry point (cmd/gibson/main.go). Deep os.Exit() calls in cobra
// command handlers or internal packages make the CLI code impossible to test
// and prevent callers from handling errors gracefully. They also bypass
// deferred cleanup (connection pool drains, temp-file removal, etc.).
//
// The correct pattern is to return an error from handler functions; the
// root cobra Execute() call in main.go receives the error and exits there.
//
// Scope: every .go file under the cli/ module root, excluding:
//   - _test.go files
//   - testdata/ directories (auto-skipped by the ast-checks harness)
//   - generated .pb.go / zz_generated*.go files
//
// Allowlist covers the canonical entry-point exit (main.go:22) and two
// pre-existing handler violations that need follow-up fixes.
//
// Implements slice 3.3 of the production-readiness epic
// (zero-day-ai/.github#50).
func TestNoOsExitInHandler(t *testing.T) {
	_, thisFile, _, _ := runtime.Caller(0)
	// thisFile is at cmd/gibson/no_os_exit_in_handler_test.go.
	// The cli/ module root is three levels up (cmd/gibson/ → cmd/ → cli/).
	moduleRoot := filepath.Join(filepath.Dir(thisFile), "..", "..")

	matchers := []astchecks.Matcher{
		astchecks.NewForbiddenCallsite(
			"os.Exit() must not be called outside cmd/gibson/main.go — return errors instead",
			"os.Exit",
		),
	}

	// Existing-debt allowlist. Add entries here only for pre-existing
	// violations that cannot be fixed in this PR; every LEGACY-OPTIONAL
	// entry MUST carry a Reason with a tracked follow-up reference.
	//
	// Generated by the first run of this test against main on 2026-05-19.
	// Two cmd handlers call os.Exit directly; both need to be reworked to
	// return the exit code via error wrapping so cobra can handle it at the
	// top level. See the IssueURL field placeholder for the fix plan.
	allowlist := astchecks.Allowlist{
		// cmd/gibson/main.go: the one legitimate os.Exit site — translates
		// cobra's error return into a process exit code.
		"cmd/gibson/main.go:22": {
			Category: astchecks.CategoryDefensiveGuard,
			Reason:   "canonical entry-point exit: root.Execute() error → os.Exit(1); this is the intended single exit site",
		},
		// cmd/component/run.go: doRun() propagates the child's exit code
		// via os.Exit instead of a typed error.
		// Fix: introduce ExitCodeError wrapping so cobra/main handles exit.
		"cmd/gibson/cmd/component/run.go:101": {
			Category: astchecks.CategoryLegacyOptional,
			Reason:   "doRun() propagates child process exit code via os.Exit; needs ExitCodeError wrapper — fix tracked as follow-up to zero-day-ai/.github#50",
		},
		// cmd/component/validate.go: runValidate() calls os.Exit(2) on
		// validation errors instead of returning a typed error.
		// Fix: return an ExitCodeError(2) sentinel from runValidate() and
		// unwrap it in main() or root.Execute().
		"cmd/gibson/cmd/component/validate.go:64": {
			Category: astchecks.CategoryLegacyOptional,
			Reason:   "runValidate() calls os.Exit(2) on validation error; needs ExitCodeError wrapper — fix tracked as follow-up to zero-day-ai/.github#50",
		},
	}

	opts := astchecks.WalkOpts{
		ScopeDirs:     []string{moduleRoot},
		RepoRoot:      moduleRoot,
		Matchers:      matchers,
		Allowlist:     allowlist,
		SkipTestFiles: true,
		SkipGenerated: true,
	}

	findings, err := astchecks.Walk(opts)
	if err != nil {
		t.Fatalf("Walk: %v", err)
	}

	if len(findings) > 0 {
		t.Errorf("os.Exit() calls found outside the CLI entry point (forbidden):\n%s\n\n"+
			"os.Exit() inside handler or internal code:\n"+
			"  - bypasses cobra's error handling\n"+
			"  - skips deferred cleanup (connection pool drain, temp files)\n"+
			"  - prevents unit-testing the handler without subprocess tricks\n\n"+
			"Fix: return an error from the handler. For exit-code propagation,\n"+
			"wrap the code in a custom error type (e.g. ExitCodeError) and\n"+
			"unwrap it in main() or root.Execute().\n\n"+
			"If this is an unavoidable pre-existing violation, add it to the\n"+
			"allowlist in this file with a CategoryLegacyOptional tag.\n",
			astchecks.RenderFindings(findings))
	}

	t.Logf("allowlist entries: %d", len(allowlist))
	if s := astchecks.FormatAllowlistLog(allowlist); s != "" {
		t.Log(s)
	}
}
